/**
 * Would You Rather question pool.
 *
 * ⚠️ APPEND-ONLY: WyrSession stores questionIndex, so existing sessions
 * resolve by position. Never reorder or delete — only add to the end.
 * (check-game-layer verifies count + uniqueness.)
 */

export type WyrQuestion = { optionA: string; optionB: string };

export const WYR_QUESTIONS: WyrQuestion[] = [
  // ——— Original seed (indices 0–24) — do not touch ———
  { optionA: "Spontaneous road trip with no plan", optionB: "Perfectly planned vacation" },
  { optionA: "A cozy night in every weekend", optionB: "Always something new to do" },
  { optionA: "Live in the city", optionB: "Live somewhere quiet and slow" },
  { optionA: "Know what's coming", optionB: "Be surprised" },
  { optionA: "Cook dinner together every night", optionB: "Try a new restaurant every week" },
  { optionA: "Fewer, deeper friendships", optionB: "A big social circle" },
  { optionA: "Early mornings together", optionB: "Late nights together" },
  { optionA: "Travel somewhere familiar you love", optionB: "Travel somewhere totally new" },
  { optionA: "A small home that feels perfect", optionB: "A big home with room to grow" },
  { optionA: "Work from home together", optionB: "Have separate work spaces" },
  { optionA: "A dog", optionB: "A cat" },
  { optionA: "Save aggressively and retire early", optionB: "Spend freely and work longer" },
  { optionA: "Live close to family", optionB: "Build your own world somewhere new" },
  { optionA: "Slow Sunday mornings", optionB: "Active weekend adventures" },
  { optionA: "Know exactly what you want", optionB: "Be open to anything" },
  { optionA: "A career that excites you", optionB: "A job that funds your real life" },
  { optionA: "Beach vacation", optionB: "Mountain getaway" },
  { optionA: "Watch something together every night", optionB: "Read in the same room" },
  { optionA: "Buy the thing you love", optionB: "Save and wait" },
  { optionA: "Take the leap and figure it out", optionB: "Plan carefully before moving" },
  { optionA: "Always have music on", optionB: "Comfortable silence" },
  { optionA: "Celebrate every little win", optionB: "Save the big celebrations for big things" },
  { optionA: "Move abroad for a year", optionB: "Stay and build deeper roots" },
  { optionA: "Have a tight daily routine", optionB: "Go with the flow each day" },
  { optionA: "Know your partner's every thought", optionB: "Keep a little mystery" },

  // ——— Everyday life & habits ———
  { optionA: "Breakfast in bed", optionB: "Midnight snack run" },
  { optionA: "Shower together to save time", optionB: "Long baths on your own schedule" },
  { optionA: "Split every chore down the middle", optionB: "Each own the ones you hate least" },
  { optionA: "One shared calendar for everything", optionB: "Figure it out as you go" },
  { optionA: "Always be ten minutes early", optionB: "Slide in right on time" },
  { optionA: "A perfectly tidy home", optionB: "A lived-in home with stories on every surface" },
  { optionA: "Coffee made for you every morning", optionB: "Dinner handled every night" },
  { optionA: "Grocery shop together weekly", optionB: "Trade off and surprise each other" },
  { optionA: "The same cozy takeout every Friday", optionB: "Never order the same thing twice" },
  { optionA: "A no-phones dinner table", optionB: "Watching your show while you eat" },
  { optionA: "One car you share", optionB: "Two cars, total freedom" },
  { optionA: "A house full of plants", optionB: "A house full of books" },
  { optionA: "Matching pajamas unironically", optionB: "Steal each other's clothes instead" },
  { optionA: "Fall asleep to a movie", optionB: "Fall asleep to total silence" },
  { optionA: "Big bed, everyone gets space", optionB: "Small bed, always touching" },

  // ——— Love & affection ———
  { optionA: "A long hug at the door every day", optionB: "A love note hidden where you'll find it" },
  { optionA: "Hear 'I love you' every morning", optionB: "Feel it in a hundred small ways" },
  { optionA: "Hold hands everywhere", optionB: "Save affection for behind closed doors" },
  { optionA: "Be teased mercilessly and adored", optionB: "Be treated gently and adored" },
  { optionA: "A partner who remembers every date", optionB: "A partner who surprises you randomly" },
  { optionA: "Slow dance in the kitchen", optionB: "Sing badly in the car together" },
  { optionA: "Re-read your old messages together", optionB: "Write new ones for the future" },
  { optionA: "One epic anniversary a year", optionB: "Twelve tiny celebrations" },
  { optionA: "Your song playing everywhere you go", optionB: "A new song for every season of you two" },
  { optionA: "Compliments in public", optionB: "Whispered ones only you hear" },
  { optionA: "A bear-hug greeting", optionB: "A kiss-on-the-forehead greeting" },
  { optionA: "Love letters once a year", optionB: "Good-morning texts every day" },
  { optionA: "Be the big spoon", optionB: "Be the little spoon" },
  { optionA: "Know exactly why they love you", optionB: "Be delightfully unsure how you pulled this off" },
  { optionA: "Grow old and mushy together", optionB: "Grow old and hilarious together" },

  // ——— Adventure & travel ———
  { optionA: "Overnight train through the mountains", optionB: "Red-eye flight to somewhere warm" },
  { optionA: "A cabin with no service", optionB: "A city where nobody knows you" },
  { optionA: "Learn to surf together", optionB: "Learn to ski together" },
  { optionA: "Camp under the stars", optionB: "Five-star hotel bathrobe life" },
  { optionA: "Street food in a night market", optionB: "One unforgettable tasting menu" },
  { optionA: "See the northern lights", optionB: "Swim in bioluminescent water" },
  { optionA: "Road trip with a great playlist", optionB: "Train ride with a great book" },
  { optionA: "Get lost in a foreign city on purpose", optionB: "Have a local show you everything" },
  { optionA: "A trip planned entirely by them", optionB: "A trip you plan together, spreadsheet and all" },
  { optionA: "Twenty countries, once each", optionB: "One country you know like home" },
  { optionA: "Hot springs in the snow", optionB: "Cold plunge on a hot day" },
  { optionA: "Sunrise hike", optionB: "Sunset picnic" },
  { optionA: "A tiny boat you pilot yourselves", optionB: "A big ship where everything's handled" },
  { optionA: "Vacation photos of everything", optionB: "No camera, just memory" },
  { optionA: "Airport people-watching for hours", optionB: "Board last, seconds to spare" },

  // ——— Food ———
  { optionA: "Pancakes for dinner", optionB: "Steak for breakfast" },
  { optionA: "One perfect pizza place forever", optionB: "A new cuisine every month" },
  { optionA: "Cook-off against each other", optionB: "Cook side by side, one dish" },
  { optionA: "Farmers market Saturday mornings", optionB: "24-hour diner Saturday nights" },
  { optionA: "Give up cheese", optionB: "Give up chocolate" },
  { optionA: "Their cooking, always", optionB: "Your cooking, always" },
  { optionA: "Fancy dinner in sweatpants", optionB: "Fast food in formalwear" },
  { optionA: "Share every dish", optionB: "Order your own, no forks crossing" },
  { optionA: "A garden you eat from", optionB: "A bakery you walk to" },
  { optionA: "Spicy food that hurts a little", optionB: "Comfort food that hugs you" },

  // ——— Money & future ———
  { optionA: "Win a modest amount now", optionB: "A shot at a fortune later" },
  { optionA: "Dream kitchen", optionB: "Dream backyard" },
  { optionA: "Renovate a fixer-upper together", optionB: "Move into something finished" },
  { optionA: "Retire somewhere sunny", optionB: "Retire somewhere with seasons" },
  { optionA: "One big splurge a year", optionB: "Small treats all year long" },
  { optionA: "A windfall you both spend guilt-free", optionB: "A windfall that buys future freedom" },
  { optionA: "Live rent-free with quirky neighbors", optionB: "Pay more for perfect peace" },
  { optionA: "Start a little business together", optionB: "Keep work and us separate" },
  { optionA: "A home that's always full of guests", optionB: "A home that's a private hideout" },
  { optionA: "Five-year plan on the fridge", optionB: "See where life takes us" },

  // ——— Play & hypotheticals ———
  { optionA: "Swap phones for a day", optionB: "Swap wardrobes for a day" },
  { optionA: "Read each other's minds for an hour", optionB: "Relive one shared day together" },
  { optionA: "Time-travel to your first date", optionB: "Peek at you two in twenty years" },
  { optionA: "Be famous as a couple", optionB: "Be completely anonymous together" },
  { optionA: "Always win arguments", optionB: "Always know when to stop arguing" },
  { optionA: "A pause button for perfect moments", optionB: "A rewind button for dumb ones" },
  { optionA: "You two in a heist movie", optionB: "You two in a cooking show" },
  { optionA: "Teleport anywhere, together only", optionB: "Fly, but solo" },
  { optionA: "Speak every language on vacation", optionB: "Understand each other perfectly at home" },
  { optionA: "A robot that does all chores", optionB: "A chef who cooks all meals" },
  { optionA: "Your pet could talk for a day", optionB: "You could read your pet's mind forever" },
  { optionA: "Live in your favorite show", optionB: "Cast your favorite actors as you two" },
  { optionA: "Karaoke duet in public", optionB: "Choreographed dance at a wedding" },
  { optionA: "Win every board game forever", optionB: "Never lose a bet against them again" },
  { optionA: "A do-over on your worst date", optionB: "A sequel to your best one" },

  // ——— Home & seasons ———
  { optionA: "Thunderstorm from the porch", optionB: "Snow day with nowhere to be" },
  { optionA: "Decorate big for every holiday", optionB: "One quiet tradition done perfectly" },
  { optionA: "A fireplace", optionB: "A bathtub with a view" },
  { optionA: "Summer person forever", optionB: "Autumn person forever" },
  { optionA: "Neighborhood where everyone knows you", optionB: "Building where nobody bothers you" },
  { optionA: "A reading nook built for two", optionB: "A hammock built for one (you fight for it)" },
  { optionA: "Host every holiday", optionB: "Always be the guests" },
  { optionA: "String lights all year", optionB: "Candles every night" },
  { optionA: "A window seat with morning sun", optionB: "A balcony with evening air" },
  { optionA: "New Year's Eve out, sparkling", optionB: "New Year's Eve in, pajamas" },

  // ——— Social & family ———
  { optionA: "Double dates every month", optionB: "Just-us dates, always" },
  { optionA: "A huge chaotic family holiday", optionB: "A tiny quiet one, just you two" },
  { optionA: "Be the couple that hosts game night", optionB: "Be the couple that always wins game night" },
  { optionA: "Friends who drop by unannounced", optionB: "Plans made two weeks out" },
  { optionA: "A group chat that never sleeps", optionB: "Three friends you call for real" },
  { optionA: "Your families vacation together", optionB: "Vacations are a family-free zone" },
  { optionA: "Big wedding energy at every party", optionB: "Irish exit as a team, every time" },
  { optionA: "Be known as the funny couple", optionB: "Be known as the couple that's got it together" },
  { optionA: "Take the couple's cooking class", optionB: "Take the couple's dance class" },
  { optionA: "Matching Halloween costumes, committed", optionB: "Never coordinate anything, ever" },

  // ——— A little deeper (still light) ———
  { optionA: "Talk all night by accident", optionB: "Sit in silence that says everything" },
  { optionA: "Be told hard truths gently", optionB: "Be told gentle truths honestly" },
  { optionA: "Grow more alike over time", optionB: "Stay wonderfully different" },
  { optionA: "A partner who asks how you really are", optionB: "A partner who already knows" },
  { optionA: "Relive your best year together", optionB: "Skip ahead to see what you built" },
  { optionA: "Always know what they need", optionB: "Always be asked what you need" },
  { optionA: "Laugh until you cry once a week", optionB: "One deep talk that changes things monthly" },
  { optionA: "Be understood without explaining", optionB: "Be asked great questions forever" },
  { optionA: "Keep every ticket stub and photo", optionB: "Keep nothing, remember everything" },
  { optionA: "Your love story as a movie", optionB: "Your love story stays just yours" },

  // ——— Rapid-fire this-or-that ———
  { optionA: "Window seat", optionB: "Aisle seat" },
  { optionA: "Sweet breakfast", optionB: "Savory breakfast" },
  { optionA: "Ocean sounds", optionB: "Rain sounds" },
  { optionA: "Bookstore date", optionB: "Record store date" },
  { optionA: "Rooftop bar", optionB: "Dive bar" },
  { optionA: "Fresh sheets night", optionB: "Fresh haircut day" },
  { optionA: "Overdressed", optionB: "Underdressed" },
  { optionA: "One great photo", optionB: "A hundred blurry ones" },
  { optionA: "Live by the water", optionB: "Live near the trees" },
  { optionA: "Front row", optionB: "Back row" },
  { optionA: "Board game night", optionB: "Trivia night" },
  { optionA: "Handwritten recipe cards", optionB: "A shared folder of screenshots" },
  { optionA: "Talk on the phone for hours", optionB: "Voice notes back and forth all day" },
  { optionA: "The house with the porch", optionB: "The apartment with the view" },
  { optionA: "A little late and relaxed", optionB: "Very early and calm" },
];
